{
 "title": "FPGA 0xBitcoin",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hashrate@Miner",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "GHs",
   "valueName": "current",
   "targets": [
    { "expr": "hashrate{card='fpga'}" }
   ]
  },
  {
   "title": "1 hour average @ miner",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "GHs",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(hashrate{card='fpga'}[1h])"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    { "expr": "temperature{card='fpga'}" }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "errors{card='fpga'}" }
   ]
  },
  {
   "title": "Voltage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "voltage{card='fpga'}" }
   ]
  },
  {
   "title": "Hashrate@Pool",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "GHs",
   "valueName": "current",
   "targets": [
    { "expr": "pool_hashrate" }
   ]
  },
  {
   "title": "1 hour average @ pool",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "GHs",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(pool_hashrate[1h])\n"
    }
   ]
  },
  {
   "title": "Clock Frequency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "clock_speed{card='fpga'}" }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "GHs" }
   ],
   "targets": [
    { "expr": "hashrate{card='fpga'}", "legendFormat": "hashrate" },
    {
     "expr": "avg_over_time(hashrate{card='fpga'}[15m])\n",
     "legendFormat": "average hashrate over 15 minutes"
    },
    {
     "expr": "avg_over_time(hashrate{card='fpga'}[1h])",
     "legendFormat": "average hashrate over 1 hour"
    },
    {}
   ]
  },
  {
   "title": "Miner vs Pool hashrates",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "GHs" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(hashrate{card='fpga'}[1h])",
     "legendFormat": "Miner hashrate 1 hour average"
    },
    {
     "expr": "avg_over_time(pool_hashrate[1h])",
     "legendFormat": "Pool hashrate 1 hour average"
    }
   ]
  },
  {
   "title": "Temperature and Errors (5 minute average)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(temperature{card='fpga'}[5m])",
     "legendFormat": "Temperature"
    },
    {
     "expr": "avg_over_time(errors{card='fpga'}[5m])",
     "legendFormat": "FPGA errors"
    }
   ]
  },
  {
   "title": "Pool Hashrate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "GHs" }
   ],
   "targets": [
    { "expr": "fpga2_pool_hashrate", "legendFormat": "Hashrate" },
    {
     "expr": "avg_over_time(pool_hashrate[15m])",
     "legendFormat": "15 minute average"
    },
    {
     "expr": "avg_over_time(pool_hashrate[1h])",
     "legendFormat": "1 hour average"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "errors{card='fpga'}", "legendFormat": "Errors" },
    {
     "expr": "avg_over_time(errors{card='fpga'}[15m])",
     "legendFormat": "Errors 15m average"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "voltage{card='fpga'}", "legendFormat": "Voltage" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "temperature{card='fpga'}", "legendFormat": "Temperature" },
    {
     "expr": "avg_over_time(temperature{card='fpga'}[15m])",
     "legendFormat": "Temperature over 15m"
    },
    {
     "expr": "avg_over_time(temperature{card='fpga'}[1h])\n",
     "legendFormat": "Temperature over 1 hour"
    }
   ]
  },
  {
   "title": "Comparisons",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true
  }
 ]
}