{
 "title": "FPGA",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hashrate@Miner",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "GHs",
   "valueName": "current",
   "targets": [
    { "expr": "hashrate{card='fpga'}" }
   ]
  },
  {
   "title": "1 hour average @ miner",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "GHs",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(hashrate{card='fpga'}[1h])"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    { "expr": "temperature{card='fpga'}" }
   ]
  },
  {
   "title": "Share Errors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "share_percent{card='fpga'}" }
   ]
  },
  {
   "title": "Solution Errors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "errors{card='fpga'}" }
   ]
  },
  {
   "title": "Clock Frequency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "clock_speed{card='fpga'}" }
   ]
  },
  {
   "title": "Last Seen",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    { "expr": "last_update{card='fpga'}" }
   ]
  },
  {
   "title": "Bad Shares",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "share_bad{card='fpga'}\n" }
   ]
  },
  {
   "title": "Total Shares",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "share_total{card='fpga'}\n" }
   ]
  },
  {
   "title": "Voltage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "voltage{card='fpga'}" }
   ]
  },
  {
   "title": "Shares Good",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "share_good{card='fpga'}\n" }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "GHs" }
   ],
   "targets": [
    { "expr": "hashrate{card='fpga'}", "legendFormat": "hashrate" },
    {
     "expr": "avg_over_time(hashrate{card='fpga'}[15m])\n",
     "legendFormat": "average hashrate over 15 minutes"
    },
    {
     "expr": "avg_over_time(hashrate{card='fpga'}[1h])",
     "legendFormat": "average hashrate over 1 hour"
    },
    {
     "expr": "avg_over_time(hashrate{card=\"fpga\"}[6h])",
     "legendFormat": "average hashrate over 6 hours"
    }
   ]
  },
  {
   "title": "Share Failure Rate",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(share_bad{card='fpga'}[15m])",
     "legendFormat": "Rate (15m)"
    },
    {
     "expr": "irate(share_bad{card='fpga'}[15m])",
     "legendFormat": "Instant Rate"
    }
   ]
  },
  {
   "title": "Temperature and Errors (5 minute average)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(temperature{card='fpga'}[5m])",
     "legendFormat": "Temperature"
    },
    {
     "expr": "avg_over_time(errors{card='fpga'}[5m])",
     "legendFormat": "FPGA errors"
    }
   ]
  },
  {
   "title": "Hashrate vs Clock speed",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hashrate{card='fpga'}", "legendFormat": "Hashrate" },
    { "expr": "clock_speed{card='fpga'}", "legendFormat": "Clock Speed" }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "errors{card='fpga'}", "legendFormat": "Errors" },
    {
     "expr": "avg_over_time(errors{card='fpga'}[15m])",
     "legendFormat": "Errors 15m average"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "temperature{card='fpga'}", "legendFormat": "Temperature" },
    {
     "expr": "avg_over_time(temperature{card='fpga'}[15m])",
     "legendFormat": "Temperature over 15m"
    },
    {
     "expr": "avg_over_time(temperature{card='fpga'}[1h])\n",
     "legendFormat": "Temperature over 1 hour"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "voltage{card='fpga'}", "legendFormat": "Voltage" }
   ]
  }
 ]
}